services:

  monsters:
    image: monsters-api
    container_name: monsters-api
    build:
      context: ./monsters
    ports:
      - 8001:8001
    environment:
      - SERVER_PORT=8080
      - environment=dev
    volumes:
      - ./tmp/npm:/root/.npm:z
      - ./monsters/src:/usr/src/app/src:z
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    container_name: monsters-db
    volumes:
      - ~/mongo/data:/data/db

  redis:
    container_name: cache
    restart: always
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ~/cache:/data