apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "mongodb-pvc"
  namespace: "development"
  labels:
    app: "mongo-db"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
---
apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "mongo"
  namespace: "development"
spec:
  serviceName: "mongo"
  replicas: 1
  selector:
    matchLabels:
      app: "mongo"
  template:
    metadata:
      labels:
        app: "mongo"
    spec:
      containers:
        -
          name: "mongo"
          image: "mongo:latest"
          imagePullPolicy: "Always"
          ports:
            -
              containerPort: 27017
              name: "mongodb"

          volumeMounts:
            -
              name: "mongodb-persistent-storage"
              mountPath: "/data/db"

      volumes:
        -
          name: "mongodb-persistent-storage"
          persistentVolumeClaim:
            claimName: "mongodb-pvc"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "mongo"
  namespace: "development"
  labels:
    app: "mongo"
spec:
  ports:
    -
      name: "mongodb"
      port: 27017
      targetPort: 27017
  clusterIP: "None"
  selector:
    app: "mongo-db"