apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: {{CONTAINER_REGISTRY}}/users:{{VERSION}}
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVER_PORT
              value: "8001"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: MONGO_HOST
              value: mongo
            - name: MONGO_PORT
              value: "27017"
---
apiVersion: v1
kind: Service
metadata:
  name: users
spec:
  selector:
    app: users
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001