name: Monsters UI CI

on:
  push:
    branches: [ "master" ]
    paths:
      - 'monsters-ui/**'
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ "master" ]
    paths:
      - 'monsters-ui/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./monsters-ui

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: NODE_ENV=development npm run build
#      - run: NODE_ENV=development npm run test
